import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";

import { MotionConfigProvider, ScrollProgressProvider } from "@/components/motion";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { AmbientBackground, AmbientProvider } from "@/features/ambient";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${GeistSans.variable} ${GeistMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <MotionConfigProvider>
            <ScrollProgressProvider>
              <AmbientProvider>
                <AmbientBackground />
                {children}
              </AmbientProvider>
            </ScrollProgressProvider>
          </MotionConfigProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
